// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jggklcroxtxhsibrugsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpnZ2tsY3JveHR4aHNpYnJ1Z3N4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MDI4OTksImV4cCI6MjA3NDI3ODg5OX0.AxPg0hBxC_7tmNp8rRWPoTF2K86nxw3UW4TFu3xGQT0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});